version: '3.8'
services:
  php5_container:
    container_name: Php_${PHP5_VERSION}-fpm
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_php5
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        PHP5_VERSION: ${PHP5_VERSION}
        PHP5_PATH_ROOT: ${PHP5_PATH_ROOT}
        PHP5_VH_NAME: ${PHP5_VH_NAME}
        PHP5_PORT_FPM: ${PHP5_PORT_FPM}
        PHP5_KEY_XDEBUG: ${PHP5_KEY_XDEBUG}
        PHP5_HOST_XDEBUG: ${PHP5_HOST_XDEBUG}
        PHP5_PORT_XDEBUG: ${PHP5_PORT_XDEBUG}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      PHP5_VERSION: ${PHP5_VERSION}
      PHP5_PATH_ROOT: ${PHP5_PATH_ROOT}
      PHP5_VH_NAME: ${PHP5_VH_NAME}
      PHP5_PORT_FPM: ${PHP5_PORT_FPM}
      PHP5_KEY_XDEBUG: ${PHP5_KEY_XDEBUG}
      PHP5_HOST_XDEBUG: ${PHP5_HOST_XDEBUG}
      PHP5_PORT_XDEBUG: ${PHP5_PORT_XDEBUG}
    ports:
      - 127.0.0.1:${PHP5_PORT_FPM}:${PHP5_PORT_FPM}
      - 127.0.0.1:${PHP5_PORT_XDEBUG}:${PHP5_PORT_XDEBUG}
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
    networks:
      default:
        ipv4_address: ${PHP5_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  php7_container:
    container_name: Php_${PHP7_VERSION}-fpm
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_php7
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        PHP7_VERSION: ${PHP7_VERSION}
        PHP7_PATH_ROOT: ${PHP7_PATH_ROOT}
        PHP7_VH_NAME: ${PHP7_VH_NAME}
        PHP7_PORT_FPM: ${PHP7_PORT_FPM}
        PHP7_KEY_XDEBUG: ${PHP7_KEY_XDEBUG}
        PHP7_HOST_XDEBUG: ${PHP7_HOST_XDEBUG}
        PHP7_PORT_XDEBUG: ${PHP7_PORT_XDEBUG}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      PHP7_VERSION: ${PHP7_VERSION}
      PHP7_PATH_ROOT: ${PHP7_PATH_ROOT}
      PHP7_VH_NAME: ${PHP7_VH_NAME}
      PHP7_PORT_FPM: ${PHP7_PORT_FPM}
      PHP7_KEY_XDEBUG: ${PHP7_KEY_XDEBUG}
      PHP7_HOST_XDEBUG: ${PHP7_HOST_XDEBUG}
      PHP7_PORT_XDEBUG: ${PHP7_PORT_XDEBUG}
    ports:
      - 127.0.0.1:${PHP7_PORT_FPM}:${PHP7_PORT_FPM}
      - 127.0.0.1:${PHP7_PORT_XDEBUG}:${PHP7_PORT_XDEBUG}
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
    networks:
      default:
        ipv4_address: ${PHP7_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  apache_container:
    container_name: Apache_${APACHE_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_apache
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        CERTIFICATE_FILE: ${CERTIFICATE_FILE}
        CERTIFICATE_KEY: ${CERTIFICATE_KEY}
        CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
        DOMAIN: ${DOMAIN}
        APACHE_VERSION: ${APACHE_VERSION}
        APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
        APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
        APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
        PHP5_VH_NAME: ${PHP5_VH_NAME}
        PHP5_PORT_FPM: ${PHP5_PORT_FPM}
        PHP7_VH_NAME: ${PHP7_VH_NAME}
        PHP7_PORT_FPM: ${PHP7_PORT_FPM}
        NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
        NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      CERTIFICATE_FILE: ${CERTIFICATE_FILE}
      CERTIFICATE_KEY: ${CERTIFICATE_KEY}
      CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
      DOMAIN: ${DOMAIN}
      APACHE_VERSION: ${APACHE_VERSION}
      APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
      APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
      APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
      PHP5_VH_NAME: ${PHP5_VH_NAME}
      PHP5_PORT_FPM: ${PHP5_PORT_FPM}
      PHP7_VH_NAME: ${PHP7_VH_NAME}
      PHP7_PORT_FPM: ${PHP7_PORT_FPM}
      NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
      NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
    ports:
      - 127.0.0.1:${APACHE_PORT_HTTP}:80
      - 127.0.0.1:${APACHE_PORT_HTTPS}:443
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${PATH_ROOT}:${APACHE_PATH_ROOT}/htdocs
    networks:
      default:
        ipv4_address: ${APACHE_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  mysql56_container:
    container_name: MySql_5.6
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_mysql56
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL56_VERSION: ${MYSQL56_VERSION}
        MYSQL56_PORT: ${MYSQL56_PORT}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL56_VERSION: ${MYSQL56_VERSION}
      MYSQL56_PORT: ${MYSQL56_PORT}
    ports:
      - 127.0.0.1:${MYSQL56_PORT}:3306
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${MYSQL56_DATA_PATH}:/var/lib/mysql
    networks:
      default:
        ipv4_address: ${MYSQL56_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  mysql57_container:
    container_name: MySql_5.7
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_mysql57
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL57_VERSION: ${MYSQL57_VERSION}
        MYSQL57_PORT: ${MYSQL57_PORT}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL57_VERSION: ${MYSQL57_VERSION}
      MYSQL57_PORT: ${MYSQL57_PORT}
    ports:
      - 127.0.0.1:${MYSQL57_PORT}:3306
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${MYSQL57_DATA_PATH}:/var/lib/mysql
    networks:
      default:
        ipv4_address: ${MYSQL57_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  postgresql_container:
    container_name: PostgreSql_${POSTGRES_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_postgresql
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: ${POSTGRES_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  nodejs_container:
    container_name: NodeJs_${NODEJS_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_nodejs
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        CERTIFICATE_FILE: ${CERTIFICATE_FILE}
        CERTIFICATE_KEY: ${CERTIFICATE_KEY}
        CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
        NODEJS_VERSION: ${NODEJS_VERSION}
        NODEJS_ENV: ${NODEJS_ENV}
        NODEJS_DOMAIN: ${NODEJS_DOMAIN}
        NODEJS_IP: ${NODEJS_IP}
        NODEJS_PATH_STATIC: ${NODEJS_PATH_STATIC}
        NODEJS_DEBUG: ${NODEJS_DEBUG}
        NODEJS_DIGEST: ${NODEJS_DIGEST}
        NODEJS_CRYPT_KEY: ${NODEJS_CRYPT_KEY}
        NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
        NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
        NODEJS_PORT_VUE: ${NODEJS_PORT_VUE}
        NODEJS_PORT_RANGE: ${NODEJS_PORT_RANGE}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      CERTIFICATE_FILE: ${CERTIFICATE_FILE}
      CERTIFICATE_KEY: ${CERTIFICATE_KEY}
      CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
      NODEJS_VERSION: ${NODEJS_VERSION}
      NODEJS_ENV: ${NODEJS_ENV}
      NODEJS_DOMAIN: ${NODEJS_DOMAIN}
      NODEJS_IP: ${NODEJS_IP}
      NODEJS_PATH_STATIC: ${NODEJS_PATH_STATIC}
      NODEJS_DEBUG: ${NODEJS_DEBUG}
      NODEJS_DIGEST: ${NODEJS_DIGEST}
      NODEJS_CRYPT_KEY: ${NODEJS_CRYPT_KEY}
      NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
      NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
      NODEJS_PORT_VUE: ${NODEJS_PORT_VUE}
      NODEJS_PORT_RANGE: ${NODEJS_PORT_RANGE}
    ports:
      - 127.0.0.1:${NODEJS_PORT_HTTP}:${NODEJS_PORT_HTTP}
      - 127.0.0.1:${NODEJS_PORT_HTTPS}:${NODEJS_PORT_HTTPS}
      - 127.0.0.1:${NODEJS_PORT_VUE}:${NODEJS_PORT_VUE}
      - 127.0.0.1:${NODEJS_PORT_RANGE}:${NODEJS_PORT_RANGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${NODEJS_DATA_PATH}:/home/link_root
    networks:
      default:
        ipv4_address: ${NODEJS_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  redis_container:
    container_name: Redis_${REDIS_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_redis
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        REDIS_VERSION: ${REDIS_VERSION}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      REDIS_VERSION: ${REDIS_VERSION}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${REDIS_DATA_PATH}:/data
    networks:
      default:
        ipv4_address: ${REDIS_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
  mongodb_container:
    container_name: MongoDb_${MONGODB_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_mongodb
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_PATH: ${WEB_PATH}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        MONGODB_VERSION: ${MONGODB_VERSION}
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
        MONGODB_DATABASE: ${MONGODB_DATABASE}
        MONGODB_USER: ${MONGODB_USER}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
        MONGODB_PORT: ${MONGODB_PORT}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      WEB_PATH: ${WEB_PATH}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      MONGODB_VERSION: ${MONGODB_VERSION}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_PORT: ${MONGODB_PORT}
    ports:
      - 127.0.0.1:${MONGODB_PORT}:27017
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
      - ${MONGODB_DATA_PATH}:/data/db
    networks:
      default:
        ipv4_address: ${MONGODB_NETWORK_IP}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
networks:
  default:
    driver: ${NETWORK_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUB}
