version: '3.8'
services:
  php5_container:
    container_name: Php_${PHP5_VERSION}-fpm
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_php5
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        PHP5_VERSION: ${PHP5_VERSION}
        PHP5_PORT_FPM: ${PHP5_PORT_FPM}
        PHP5_PORT_XDEBUG: ${PHP5_PORT_XDEBUG}
        PHP5_PATH_ROOT: ${PHP5_PATH_ROOT}
        PHP5_VH_NAME: ${PHP5_VH_NAME}
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      PHP5_VERSION: ${PHP5_VERSION}
      PHP5_PORT_FPM: ${PHP5_PORT_FPM}
      PHP5_PORT_XDEBUG: ${PHP5_PORT_XDEBUG}
      PHP5_PATH_ROOT: ${PHP5_PATH_ROOT}
      PHP5_VH_NAME: ${PHP5_VH_NAME}
    ports:
      - ${PHP5_PORT_FPM}:${PHP5_PORT_FPM}
      - ${PHP5_PORT_XDEBUG}:${PHP5_PORT_XDEBUG}
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
  php7_container:
    container_name: Php_${PHP7_VERSION}-fpm
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_php7
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        PHP7_VERSION: ${PHP7_VERSION}
        PHP7_PORT_FPM: ${PHP7_PORT_FPM}
        PHP7_PORT_XDEBUG: ${PHP7_PORT_XDEBUG}
        PHP7_PATH_ROOT: ${PHP7_PATH_ROOT}
        PHP7_VH_NAME: ${PHP7_VH_NAME}
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      PHP7_VERSION: ${PHP7_VERSION}
      PHP7_PORT_FPM: ${PHP7_PORT_FPM}
      PHP7_PORT_XDEBUG: ${PHP7_PORT_XDEBUG}
      PHP7_PATH_ROOT: ${PHP7_PATH_ROOT}
      PHP7_VH_NAME: ${PHP7_VH_NAME}
    ports:
      - ${PHP7_PORT_FPM}:${PHP7_PORT_FPM}
      - ${PHP7_PORT_XDEBUG}:${PHP7_PORT_XDEBUG}
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
  apache_container:
    container_name: Apache_${APACHE_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_apache
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        APACHE_VERSION: ${APACHE_VERSION}
        APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
        APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
        APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
        PHP5_PORT_FPM: ${PHP5_PORT_FPM}
        PHP5_VH_NAME: ${PHP5_VH_NAME}
        PHP7_PORT_FPM: ${PHP7_PORT_FPM}
        PHP7_VH_NAME: ${PHP7_VH_NAME}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      APACHE_VERSION: ${APACHE_VERSION}
      APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
      APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
      APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
      PHP5_PORT_FPM: ${PHP5_PORT_FPM}
      PHP5_VH_NAME: ${PHP5_VH_NAME}
      PHP7_PORT_FPM: ${PHP7_PORT_FPM}
      PHP7_VH_NAME: ${PHP7_VH_NAME}
    ports:
      - ${APACHE_PORT_HTTP}:80
      - ${APACHE_PORT_HTTPS}:443
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
      - ${PATH_ROOT}:${APACHE_PATH_ROOT}/htdocs
    depends_on:
      - php5_container
      - php7_container
  mysql_container:
    container_name: MySql_${MYSQL_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_mysql
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      MYSQL_VERSION: ${MYSQL_VERSION}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
    depends_on:
      - apache_container
  postgresql_container:
    container_name: PostgreSql_${POSTGRES_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_postgresql
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
    depends_on:
      - apache_container
  nodejs_container:
    container_name: NodeJs_${NODEJS_VERSION}
    build:
      context: ${PATH_ROOT}/docker
      dockerfile: Dockerfile_nodejs
      args:
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        NODEJS_OS_VERSION: ${NODEJS_OS_VERSION}
        NODEJS_VERSION: ${NODEJS_VERSION}
        NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
        NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
        NODEJS_PORT_VUE: ${NODEJS_PORT_VUE}
        NODEJS_PORT_VUE_APP: ${NODEJS_PORT_VUE_APP}
        NODEJS_PATH_SERVER: ${NODEJS_PATH_SERVER}
    environment:
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      NODEJS_OS_VERSION: ${NODEJS_OS_VERSION}
      NODEJS_VERSION: ${NODEJS_VERSION}
      NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
      NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
      NODEJS_PORT_VUE: ${NODEJS_PORT_VUE}
      NODEJS_PORT_VUE_APP: ${NODEJS_PORT_VUE_APP}
      NODEJS_PATH_SERVER: ${NODEJS_PATH_SERVER}
    ports:
      - ${NODEJS_PORT_HTTP}:${NODEJS_PORT_HTTP}
      - ${NODEJS_PORT_HTTPS}:${NODEJS_PORT_HTTPS}
      - ${NODEJS_PORT_VUE}:${NODEJS_PORT_VUE}
      - ${NODEJS_PORT_VUE_APP}:${NODEJS_PORT_VUE_APP}
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www