version: "3.8"
services:
  one_workspace:
    container_name: one-workspace
    build:
      context: ./
      dockerfile: ./docker/${DOCKERFILE}
      args:
        _NODEJS_VERSION: ${NODEJS_VERSION}
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIMEZONE: ${TIMEZONE}
        _SERVER_PORT: ${SERVER_PORT}
        _SERVER_PORT_RANGE: ${SERVER_PORT_RANGE}
        _NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
    env_file:
      - ./env/local.env
    ports:
      - 127.0.0.1:${SERVER_PORT}:${SERVER_PORT}
      - 127.0.0.1:${SERVER_PORT_RANGE}:${SERVER_PORT_RANGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/root/
      - /tmp/.X11-unix:/tmp/.X11-unix
