version: '3.8'
services:
  php_container:
    container_name: Php_${PHP_VERSION}-fpm
    build:
      context: ${PATH_ROOT}/_system/docker
      dockerfile: Dockerfile_php
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        SSH_GROUP: ${SSH_GROUP}
        SSH_PORT: ${SSH_PORT}
        PHP_VERSION: ${PHP_VERSION}
        PHP_PORT_FPM: ${PHP_PORT_FPM}
        PHP_PORT_XDEBUG: ${PHP_PORT_XDEBUG}
        PHP_PATH_ROOT: ${PHP_PATH_ROOT}
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      SSH_GROUP: ${SSH_GROUP}
      SSH_PORT: ${SSH_PORT}
      PHP_VERSION: ${PHP_VERSION}
      PHP_PORT_FPM: ${PHP_PORT_FPM}
      PHP_PORT_XDEBUG: ${PHP_PORT_XDEBUG}
      PHP_PATH_ROOT: ${PHP_PATH_ROOT}
    ports:
      - ${SSH_PORT}:22
      - ${PHP_PORT_FPM}:9000
      - ${PHP_PORT_XDEBUG}:9999
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
  apache_container:
    container_name: Apache_${APACHE_VERSION}
    build:
      context: ${PATH_ROOT}/_system/docker
      dockerfile: Dockerfile_apache
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        APACHE_VERSION: ${APACHE_VERSION}
        APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
        APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
        APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
        PHP_VERSION: ${PHP_VERSION}
        PHP_PORT_FPM: ${PHP_PORT_FPM}
        PHP_PORT_XDEBUG: ${PHP_PORT_XDEBUG}
        PHP_PATH_ROOT: ${PHP_PATH_ROOT}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      APACHE_VERSION: ${APACHE_VERSION}
      APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
      APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
      APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
      PHP_VERSION: ${PHP_VERSION}
      PHP_PORT_FPM: ${PHP_PORT_FPM}
      PHP_PORT_XDEBUG: ${PHP_PORT_XDEBUG}
      PHP_PATH_ROOT: ${PHP_PATH_ROOT}
    ports:
      - ${APACHE_PORT_HTTP}:80
      - ${APACHE_PORT_HTTPS}:443
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
      - ${PATH_ROOT}:${APACHE_PATH_ROOT}/htdocs
    depends_on:
      - php_container
  mysql_container:
    container_name: MySql_${MYSQL_VERSION}
    build:
      context: ${PATH_ROOT}/_system/docker
      dockerfile: Dockerfile_mysql
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      MYSQL_VERSION: ${MYSQL_VERSION}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
    depends_on:
      - apache_container
  postgresql_container:
    container_name: PostgreSql_${POSTGRES_VERSION}
    build:
      context: ${PATH_ROOT}/_system/docker
      dockerfile: Dockerfile_postgresql
      args:
        WWW_USER_NAME: ${WWW_USER_NAME}
        WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      WWW_USER_NAME: ${WWW_USER_NAME}
      WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
      WEB_USER_GROUP: ${WEB_USER_GROUP}
      PATH_ROOT: ${PATH_ROOT}
      TIMEZONE: ${TIMEZONE}
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${PATH_ROOT}:/home/${WWW_USER_NAME}/www
    depends_on:
      - apache_container
  nodejs_container:
    command: "tail -f /dev/null"
    container_name: NodeJs_${NODEJS_VERSION}
    build:
      context: ${PATH_ROOT}/_system/docker
      dockerfile: Dockerfile_nodejs
      args:
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        NODEJS_VERSION: ${NODEJS_VERSION}
        NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
        NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
    environment:
        PATH_ROOT: ${PATH_ROOT}
        TIMEZONE: ${TIMEZONE}
        NODEJS_VERSION: ${NODEJS_VERSION}
        NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
        NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
    ports:
      - ${NODEJS_PORT_HTTP}:1080
      - ${NODEJS_PORT_HTTPS}:1443
    volumes:
      - ${PATH_ROOT}:${NODEJS_PATH_ROOT}