version: "3.8"
services:
  ow_nodejs:
    container_name: ow-nodejs
    env_file:
      - ./env/local.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_nodejs
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIMEZONE: ${TIMEZONE}
        _SERVER_LOCATION: ${SERVER_LOCATION}
        _PATH_ROOT: ${PATH_ROOT}
        _NODEJS_VERSION: ${NODEJS_VERSION}
        _NODEJS_SERVER_PORT: ${NODEJS_SERVER_PORT}
        _NODEJS_SERVER_PORT_RANGE: ${NODEJS_SERVER_PORT_RANGE}
    ports:
      - 127.0.0.1:${NODEJS_SERVER_PORT}:${NODEJS_SERVER_PORT}
      - 127.0.0.1:${NODEJS_SERVER_PORT_RANGE}:${NODEJS_SERVER_PORT_RANGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:${PATH_ROOT}
      - /tmp/.X11-unix:/tmp/.X11-unix
  ow_python:
    container_name: ow-python
    env_file:
      - ./env/local.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_python
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIMEZONE: ${TIMEZONE}
        _SERVER_LOCATION: ${SERVER_LOCATION}
        _PATH_ROOT: ${PATH_ROOT}
        _PYTHON_VERSION: ${PYTHON_VERSION}
        _PYTHON_JUPYTER_PORT: ${PYTHON_JUPYTER_PORT}
    ports:
      - 127.0.0.1:${PYTHON_JUPYTER_PORT}:${PYTHON_JUPYTER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:${PATH_ROOT}
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - ow_nodejs
  ow_apache:
    container_name: ow-apache
    env_file:
      - ./env/local.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_apache
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIMEZONE: ${TIMEZONE}
        _SERVER_LOCATION: ${SERVER_LOCATION}
        _PATH_ROOT: ${PATH_ROOT}
        _APACHE_VERSION: ${APACHE_VERSION}
        _APACHE_SERVER_PORT: ${APACHE_SERVER_PORT}
    ports:
      - 127.0.0.1:443:${APACHE_SERVER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:${PATH_ROOT}
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - ow_nodejs
