version: '3.8'
services:
    nodejs_container:
        container_name: NodeJs_${NODEJS_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_nodejs
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                CERTIFICATE_FILE: ${CERTIFICATE_FILE}
                CERTIFICATE_KEY: ${CERTIFICATE_KEY}
                CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
                NODEJS_VERSION: ${NODEJS_VERSION}
                NODEJS_ENV: ${NODEJS_ENV}
                NODEJS_DOMAIN: ${NODEJS_DOMAIN}
                NODEJS_IP: ${NODEJS_IP}
                NODEJS_PATH_STATIC: ${NODEJS_PATH_STATIC}
                NODEJS_DEBUG: ${NODEJS_DEBUG}
                NODEJS_DIGEST: ${NODEJS_DIGEST}
                NODEJS_ENCRYPTION_SECRET: ${NODEJS_ENCRYPTION_SECRET}
                NODEJS_ENCRYPTION_KEY: ${NODEJS_ENCRYPTION_KEY}
                NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
                NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
                NODEJS_PORT_VUE: ${NODEJS_PORT_VUE}
                NODEJS_PORT_RANGE: ${NODEJS_PORT_RANGE}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            CERTIFICATE_FILE: ${CERTIFICATE_FILE}
            CERTIFICATE_KEY: ${CERTIFICATE_KEY}
            CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
            NODEJS_VERSION: ${NODEJS_VERSION}
            NODEJS_ENV: ${NODEJS_ENV}
            NODEJS_DOMAIN: ${NODEJS_DOMAIN}
            NODEJS_IP: ${NODEJS_IP}
            NODEJS_PATH_STATIC: ${NODEJS_PATH_STATIC}
            NODEJS_DEBUG: ${NODEJS_DEBUG}
            NODEJS_DIGEST: ${NODEJS_DIGEST}
            NODEJS_ENCRYPTION_SECRET: ${NODEJS_ENCRYPTION_SECRET}
            NODEJS_ENCRYPTION_KEY: ${NODEJS_ENCRYPTION_KEY}
            NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
            NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
            NODEJS_PORT_VUE: ${NODEJS_PORT_VUE}
            NODEJS_PORT_RANGE: ${NODEJS_PORT_RANGE}
        ports:
            - 127.0.0.1:${NODEJS_PORT_HTTP}:${NODEJS_PORT_HTTP}
            - 127.0.0.1:${NODEJS_PORT_HTTPS}:${NODEJS_PORT_HTTPS}
            - 127.0.0.1:${NODEJS_PORT_VUE}:${NODEJS_PORT_VUE}
            - 127.0.0.1:${NODEJS_PORT_RANGE}:${NODEJS_PORT_RANGE}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
            - ${NODEJS_DATA_PATH}:/home/link_root
        networks:
            default:
                ipv4_address: ${NODEJS_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    apache_container:
        container_name: Apache_${APACHE_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_apache
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                CERTIFICATE_FILE: ${CERTIFICATE_FILE}
                CERTIFICATE_KEY: ${CERTIFICATE_KEY}
                CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
                DOMAIN: ${DOMAIN}
                APACHE_VERSION: ${APACHE_VERSION}
                APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
                APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
                APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
                PHP_VH_NAME: ${PHP_VH_NAME}
                PHP_PORT_FPM: ${PHP_PORT_FPM}
                NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
                NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            CERTIFICATE_FILE: ${CERTIFICATE_FILE}
            CERTIFICATE_KEY: ${CERTIFICATE_KEY}
            CERTIFICATE_CHAIN: ${CERTIFICATE_CHAIN}
            DOMAIN: ${DOMAIN}
            APACHE_VERSION: ${APACHE_VERSION}
            APACHE_PATH_ROOT: ${APACHE_PATH_ROOT}
            APACHE_PORT_HTTP: ${APACHE_PORT_HTTP}
            APACHE_PORT_HTTPS: ${APACHE_PORT_HTTPS}
            PHP_VH_NAME: ${PHP_VH_NAME}
            PHP_PORT_FPM: ${PHP_PORT_FPM}
            NODEJS_PORT_HTTP: ${NODEJS_PORT_HTTP}
            NODEJS_PORT_HTTPS: ${NODEJS_PORT_HTTPS}
        ports:
            - 127.0.0.1:${APACHE_PORT_HTTP}:80
            - 127.0.0.1:${APACHE_PORT_HTTPS}:443
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
            - ${PATH_ROOT}:${APACHE_PATH_ROOT}/htdocs
        networks:
            default:
                ipv4_address: ${APACHE_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    php_container:
        container_name: Php_${PHP_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_php
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                PHP_VERSION: ${PHP_VERSION}
                PHP_PATH_ROOT: ${PHP_PATH_ROOT}
                PHP_VH_NAME: ${PHP_VH_NAME}
                PHP_PORT_FPM: ${PHP_PORT_FPM}
                PHP_KEY_XDEBUG: ${PHP_KEY_XDEBUG}
                PHP_HOST_XDEBUG: ${PHP_HOST_XDEBUG}
                PHP_PORT_XDEBUG: ${PHP_PORT_XDEBUG}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            PHP_VERSION: ${PHP_VERSION}
            PHP_PATH_ROOT: ${PHP_PATH_ROOT}
            PHP_VH_NAME: ${PHP_VH_NAME}
            PHP_PORT_FPM: ${PHP_PORT_FPM}
            PHP_KEY_XDEBUG: ${PHP_KEY_XDEBUG}
            PHP_HOST_XDEBUG: ${PHP_HOST_XDEBUG}
            PHP_PORT_XDEBUG: ${PHP_PORT_XDEBUG}
        ports:
            - 127.0.0.1:${PHP_PORT_FPM}:${PHP_PORT_FPM}
            - 127.0.0.1:${PHP_PORT_XDEBUG}:${PHP_PORT_XDEBUG}
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
        networks:
            default:
                ipv4_address: ${PHP_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    mysql_container:
        container_name: MySql_5.7
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_mysql
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_VERSION: ${MYSQL_VERSION}
                MYSQL_PORT: ${MYSQL_PORT}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_VERSION: ${MYSQL_VERSION}
            MYSQL_PORT: ${MYSQL_PORT}
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
        networks:
            default:
                ipv4_address: ${MYSQL_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    postgresql_container:
        container_name: PostgreSql_${POSTGRES_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_postgresql
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                POSTGRES_VERSION: ${POSTGRES_VERSION}
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_PORT: ${POSTGRES_PORT}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            POSTGRES_VERSION: ${POSTGRES_VERSION}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
            - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
        networks:
            default:
                ipv4_address: ${POSTGRES_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    redis_container:
        container_name: Redis_${REDIS_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_redis
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                REDIS_VERSION: ${REDIS_VERSION}
                REDIS_PASSWORD: ${REDIS_PASSWORD}
                REDIS_PORT: ${REDIS_PORT}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            REDIS_VERSION: ${REDIS_VERSION}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_PORT: ${REDIS_PORT}
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
            - ${REDIS_DATA_PATH}:/data
        networks:
            default:
                ipv4_address: ${REDIS_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    mongodb_container:
        container_name: MongoDb_${MONGODB_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_mongodb
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                MONGODB_VERSION: ${MONGODB_VERSION}
                MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
                MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
                MONGODB_DATABASE: ${MONGODB_DATABASE}
                MONGODB_USER: ${MONGODB_USER}
                MONGODB_PASSWORD: ${MONGODB_PASSWORD}
                MONGODB_PORT: ${MONGODB_PORT}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            MONGODB_VERSION: ${MONGODB_VERSION}
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
            MONGODB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_USER: ${MONGODB_USER}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_PORT: ${MONGODB_PORT}
        ports:
            - 127.0.0.1:${MONGODB_PORT}:27017
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
            - ${MONGODB_DATA_PATH}:/data/db
        networks:
            default:
                ipv4_address: ${MONGODB_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
    python_container:
        container_name: Python_${PYTHON_VERSION}
        build:
            context: ${PATH_ROOT}/docker
            dockerfile: Dockerfile_python
            args:
                WWW_USER_NAME: ${WWW_USER_NAME}
                WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
                WEB_USER_GROUP: ${WEB_USER_GROUP}
                WEB_PATH: ${WEB_PATH}
                PATH_ROOT: ${PATH_ROOT}
                TIMEZONE: ${TIMEZONE}
                PYTHON_VERSION: ${PYTHON_VERSION}
        environment:
            WWW_USER_NAME: ${WWW_USER_NAME}
            WWW_USER_PASSWORD: ${WWW_USER_PASSWORD}
            WEB_USER_GROUP: ${WEB_USER_GROUP}
            WEB_PATH: ${WEB_PATH}
            PATH_ROOT: ${PATH_ROOT}
            TIMEZONE: ${TIMEZONE}
            PYTHON_VERSION: ${PYTHON_VERSION}
        ports:
            - 127.0.0.1:${PYTHON_PORT}:${PYTHON_PORT}
        volumes:
            - ${PATH_ROOT}:/home/${WWW_USER_NAME}/root
        networks:
            default:
                ipv4_address: ${PYTHON_NETWORK_IP}
        logging:
            options:
                max-size: ${LOG_MAX_SIZE}
                max-file: ${LOG_MAX_FILE}
networks:
    default:
        driver: ${NETWORK_DRIVER}
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUB}
