ARG PHP5_VERSION

FROM php:${PHP5_VERSION}-fpm

ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_USER_GROUP
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE
ARG PHP5_PATH_ROOT
ARG PHP5_VH_NAME
ARG PHP5_PORT_FPM
ARG PHP5_KEY_XDEBUG
ARG PHP5_HOST_XDEBUG
ARG PHP5_PORT_XDEBUG

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ${PATH_ROOT}/php5_zz-docker.conf ${PHP5_PATH_ROOT}/php-fpm.d/zz-docker.conf
COPY ${PATH_ROOT}/php5_override.ini ${PHP5_PATH_ROOT}/php/conf.d/override.ini
COPY ${PATH_ROOT}/entrypoint_php.sh /usr/local/bin/entrypoint.sh

# System
RUN cd ~ \
&& chmod +x /usr/local/bin/entrypoint.sh \
&& cp ${PHP5_PATH_ROOT}/php/php.ini-production ${PHP5_PATH_ROOT}/php/php.ini \
&& apt-get update && apt-get install -y \
software-properties-common \
sudo \
nano \
tzdata \
curl \
make \
zip \
unzip \
cron \
wget \
re2c \
file \
libfreetype6-dev \
libjpeg-dev \
libpng-dev \
libssl-dev \
libicu-dev \
libzip-dev \
zlib1g-dev \
libxml2-dev \
libpq-dev \
libmagickwand-dev \
libgmp-dev \
libmhash-dev \
libmcrypt-dev \
libmemcached-dev \
zlib1g-dev \
# Group
&& addgroup sftp \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# User www
&& useradd --home /home/${WWW_USER_NAME} -g ${WEB_USER_GROUP} -G sftp --shell /bin/false -m ${WWW_USER_NAME} \
&& echo "${WWW_USER_NAME}:${WWW_USER_PASSWORD}" | chpasswd \
&& chown root:root /home/${WWW_USER_NAME} \
&& mkdir /home/${WWW_USER_NAME}/root \
&& chown ${WWW_USER_NAME}:${WEB_USER_GROUP} /home/${WWW_USER_NAME}/root \
# Extension
&& ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/ \
&& pear config-set php_ini ${PHP5_PATH_ROOT}/php/php.ini \
&& pear config-set php_bin /usr/local/bin \
&& echo "\n" | pecl install apcu-4.0.11 \
&& echo "\n" | pecl install xdebug-2.5.5 \
&& echo "\n" | pecl install imagick-3.4.4 \
&& echo "\n" | pecl install memcached-2.2.0 \
&& docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include \
&& docker-php-ext-configure gmp \
&& docker-php-ext-install gd intl opcache zip mysql pdo pdo_mysql pdo_pgsql bcmath gmp \
# Composer
&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
# Clean
&& pecl clear-cache \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

EXPOSE ${PHP5_PORT_FPM} ${PHP5_PORT_XDEBUG}