ARG _PYTHON_VERSION

FROM python:${_PYTHON_VERSION}

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _LANG
ARG _SERVER_LOCATION
ARG _PATH_ROOT
ARG _PYTHON_JUPYTER_PORT

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}
ENV LANG=${_LANG}
ENV SERVER_LOCATION=${_SERVER_LOCATION}
ENV PATH_ROOT=${_PATH_ROOT}
ENV PYTHON_VERSION=${_PYTHON_VERSION}
ENV PYTHON_JUPYTER_PORT=${_PYTHON_JUPYTER_PORT}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV SUDO_FORCE_REMOVE=yes
ENV PATH="${PATH}:${PATH_ROOT}.local/bin/:/root/.local/bin/"
ENV PYTHONPATH="${PATH_ROOT}"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

COPY ./certificate/proxy/ /usr/local/share/ca-certificates/

RUN cd ~ \
    # No root
    && mkdir -p ${PATH_ROOT} \
    && useradd -U pyuser -d ${PATH_ROOT} -s /bin/bash \
    && chown -R pyuser:pyuser ${PATH_ROOT} \
    && chmod -R 775 ${PATH_ROOT} \
    # Update
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates curl \
    && update-ca-certificates \
    # Apt
    && apt-get update && apt-get install -y \
    fonts-noto \
    fonts-noto-cjk \
    # Clean
    && apt-get remove --purge -y sudo \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER pyuser

WORKDIR ${PATH_ROOT}

# Pip
CMD python3 -m pip install pip --upgrade \
    && python3 -m pip install --user --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org -r ${PATH_ROOT}docker/python_requirements.txt \
    # Jupyter lab
    && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''

EXPOSE ${PYTHON_JUPYTER_PORT}
