ARG MYSQL_VERSION

FROM mysql:${MYSQL_VERSION}

ARG PROXY_HTTP
ARG PROXY_HTTPS
ARG PROXY_CERTIFICATE
ARG DOCKER_PATH_ROOT
ARG TIMEZONE
ARG CERTIFICATE_FILE
ARG CERTIFICATE_KEY
ARG CERTIFICATE_CHAIN
ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_FOLDER
ARG WEB_USER_GROUP

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_PORT

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV http_proxy=${PROXY_HTTP}
ENV https_proxy=${PROXY_HTTPS}
ENV HTTP_PROXY=${PROXY_HTTP}
ENV HTTPS_PROXY=${PROXY_HTTPS}
ENV CURL_CA_BUNDLE=${PROXY_CERTIFICATE}

COPY ${DOCKER_PATH_ROOT}certificate/zscaler/* /usr/local/share/ca-certificates/
COPY ${DOCKER_PATH_ROOT}docker/mysql_override.cnf /etc/mysql/conf.d/override.cnf

# System
RUN cd ~ \
    && apt-get update && apt-get install -y \
    ca-certificates \
    software-properties-common \
    apt-transport-https \
    lsb-release \
    gnupg \
    nano \
    tzdata \
    curl \
    make \
    zip \
    unzip \
    cron \
    # Certificate
    && update-ca-certificates \
    # Time
    && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

EXPOSE ${MYSQL_PORT}
