ARG MONGODB_VERSION

FROM mongo:${MONGODB_VERSION}

ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_USER_GROUP
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE
ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ROOT_PASSWORD
ARG MONGODB_PORT

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

# System
RUN cd ~ \
&& apt-get update && apt-get install -y \
software-properties-common \
sudo \
nano \
tzdata \
curl \
make \
zip \
unzip \
cron \
wget \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

EXPOSE ${MONGODB_PORT}