ARG NODEJS_VERSION

FROM node:${NODEJS_VERSION}

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _SERVER_PORT
ARG _SERVER_PORT_RANGE
ARG _PROXY_HTTP
ARG _PROXY_HTTPS
ARG _PROXY_CERTIFICATE

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}
ENV PROXY_HTTP=${_PROXY_HTTP}
ENV PROXY_HTTPS=${_PROXY_HTTPS}
ENV NODE_EXTRA_CA_CERTS=${_PROXY_CERTIFICATE}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ./certificate/proxy/* /usr/local/share/ca-certificates/

RUN cd ~ \
    # No root
    && mkdir -p /home/root/ /usr/local/lib/node_modules/ \
    && chown -R node:node /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    && chmod 775 /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    # Apt
    && apt-get update && apt-get install -y \
    ca-certificates \
    # Certificate
    && update-ca-certificates \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER node

WORKDIR /home/root/

# Tls
CMD chmod +x /home/root/docker/tls.sh \
    && bash /home/root/docker/tls.sh \
    # Keep running
    && tail -f /dev/null

EXPOSE ${_SERVER_PORT} ${_SERVER_PORT_RANGE}
