ARG _PYTHON_VERSION

FROM python:${_PYTHON_VERSION}

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _PYTHON_JUPYTER_PORT

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV PATH="${PATH}:/home/root/.local/bin/:/root/.local/bin/"
ENV PYTHONPATH="/home/root/"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

COPY ./certificate/proxy/ /usr/local/share/ca-certificates/

RUN cd ~ \
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates gnupg curl \
    && update-ca-certificates \
    # No root
    && groupadd -g 1000 pyuser \
    && useradd -d /home/root/ -s /bin/bash -u 1000 -g 1000 pyuser \
    && mkdir -p /home/root/ \
    && chown -R pyuser:pyuser /home/root/ \
    && chmod -R 775 /home/root/ \
    # Apt
    && apt-get update && apt-get install -y \
    fonts-noto \
    fonts-noto-cjk \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER pyuser

WORKDIR /home/root/

# Pip
CMD python3 -m pip install pip --upgrade \
    && python3 -m pip install --user --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org -r /home/root/docker/python_requirements.txt \
    # Jupyter lab
    && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''

EXPOSE ${_PYTHON_JUPYTER_PORT}
