ARG REDIS_VERSION

FROM redis:${REDIS_VERSION}

ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_USER_GROUP
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE
ARG REDIS_PASSWORD
ARG REDIS_PORT

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ${PATH_ROOT}/redis.conf /usr/local/etc/redis/redis.conf

# System
RUN cd ~ \
&& apt-get update && apt-get install -y \
software-properties-common \
sudo \
nano \
tzdata \
curl \
make \
zip \
unzip \
cron \
wget \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

CMD ["sh", "-c", "redis-server --requirepass ${REDIS_PASSWORD}"]

EXPOSE ${REDIS_PORT}