ARG _NODEJS_VERSION

FROM node:${_NODEJS_VERSION}

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _SERVER_PORT
ARG _SERVER_PORT_RANGE

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

RUN cd ~ \
    # No root
    && mkdir -p /home/root/ /usr/local/lib/node_modules/ \
    && chown -R node:node /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    && chmod 775 /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    # Apt
    && apt-get update && apt-get install -y \
    ca-certificates \
    fonts-noto \
    fonts-noto-cjk \
    # Certificate
    && update-ca-certificates \
    # Tls
    && mkdir -p /var/log/one_workspace/ \
    && chown -R node:node /var/log/one_workspace/ \
    && chmod 775 /var/log/one_workspace/ \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER node

WORKDIR /home/root/

# Tls
CMD chmod +x /home/root/docker/tls.sh \
    && bash /home/root/docker/tls.sh \
    # Keep running
    && tail -f /dev/null

EXPOSE ${_SERVER_PORT} ${_SERVER_PORT_RANGE}
