FROM ubuntu:24.04

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIME_ZONE
ARG _LANG
ARG _PATH_ROOT
ARG _PYTHON_JUPYTER_PORT

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIME_ZONE}
ENV LANG=${_LANG}
ENV PATH_ROOT=${_PATH_ROOT}
ENV PYTHON_JUPYTER_PORT=${_PYTHON_JUPYTER_PORT}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV SUDO_FORCE_REMOVE=yes
ENV HISTFILE="/home/pyuser/.bash_history"
ENV PATH="${PATH_ROOT}.local/bin/:${PATH}"
ENV PYTHONPATH="${PATH_ROOT}"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV WAYLAND_DISPLAY=wayland-0
ENV XDG_SESSION_TYPE=wayland
ENV XDG_RUNTIME_DIR="/mnt/wslg/runtime-dir/"
ENV ELECTRON_ENABLE_WAYLAND=1
ENV ELECTRON_OZONE_PLATFORM_HINT=auto
ENV OZONE_PLATFORM=wayland
ENV EGL_PLATFORM=wayland
ENV ANGLE_DEFAULT_PLATFORM=egl
ENV DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}bus"
ENV PULSE_SERVER="unix:/mnt/wslg/PulseServer"
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

COPY ./certificate/ /usr/local/share/ca-certificates/
COPY ./docker/font/ /usr/share/fonts/truetype/noto/
COPY ./docker/font.conf /etc/fonts/local.conf

RUN cd ~ \
    # No root
    && userdel -r ubuntu \
    && groupadd -g 1000 pyuser \
    && useradd -m -u 1000 -g 1000 -d ${PATH_ROOT} -s /bin/bash pyuser \
    && uid="$(id -u pyuser)" \
    && mkdir -p ${PATH_ROOT} /home/pyuser/ /run/user/${uid} \
    && chown -R pyuser:pyuser ${PATH_ROOT} /home/pyuser/ /run/user/${uid} \
    && chmod -R 775 ${PATH_ROOT} /home/pyuser/ \
    && chmod -R 700 /run/user/${uid} \
    # Update
    && echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries \
    && echo 'Acquire::http::No-Cache "true";' > /etc/apt/apt.conf.d/99no-cache \
    && echo 'Acquire::https::No-Cache "true";' >> /etc/apt/apt.conf.d/99no-cache \
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates tzdata curl media-types jq gettext-base lynx \
    && update-ca-certificates \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone \
    && echo "application/typescript ts" >> /etc/mime.types \
    # Python
    && apt-get update && apt-get install -y \
    python3-pip \
    # Wslg
    && groupadd -g 110 render || true \
    && groupadd -g 44 video || true \
    && usermod -aG 110 pyuser \
    && usermod -aG 44 pyuser \
    && apt-get update && apt-get install -y \
    libglib2.0-0 \
    libgtk-3-0 \
    libcairo2 \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libxkbcommon0 \
    libfontconfig1 \
    libfreetype6 \
    libnss3 \
    libnspr4 \
    libasound2t64 \
    libgl1 \
    libglx-mesa0 \
    libgl1-mesa-dri \
    libegl1 \
    libegl1-mesa-dev \
    libegl-dev \
    libglvnd-dev \
    libgbm1 \
    mesa-va-drivers \
    mesa-utils-extra \
    libdrm2 \
    libxdamage1 \
    libxfixes3 \
    libxcomposite1 \
    libxrandr2 \
    libwayland-client0 \
    libwayland-egl1 \
    libwayland-cursor0 \
    libgomp1 \
    libatomic1 \
    xdg-utils \
    # Clean
    && apt-get remove --purge -y sudo \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER pyuser

WORKDIR ${PATH_ROOT}

CMD ["sh", "-c", "bash ${PATH_ROOT}script/gpu.sh && bash ${PATH_ROOT}script/dbus.sh && bash ${PATH_ROOT}script/engine_package.sh && bash ${PATH_ROOT}script/pip.sh && bash ${PATH_ROOT}script/jupyter_lab.sh"]

EXPOSE ${PYTHON_JUPYTER_PORT}
