ARG MYSQL_VERSION

FROM mysql:${MYSQL_VERSION}

ARG PROXY_HTTP
ARG PROXY_HTTPS
ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_USER_GROUP
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_PORT

ENV http_proxy=${PROXY_HTTP}
ENV https_proxy=${PROXY_HTTPS}
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ${PATH_ROOT}/mysql_override.cnf /etc/mysql/conf.d/override.cnf

# System
RUN cd ~ \
&& apt-get update && apt-get install -y \
software-properties-common \
apt-transport-https \
lsb-release \
sudo \
nano \
tzdata \
curl \
make \
zip \
unzip \
cron \
wget \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

EXPOSE ${MYSQL_PORT}
