ARG NODEJS_VERSION

FROM node:${NODEJS_VERSION}

ARG PATH_ROOT
ARG TIMEZONE
ARG NODEJS_PORT_HTTP
ARG NODEJS_PORT_HTTPS
ARG NODEJS_PORT_VUE
ARG NODEJS_PORT_VUE_APP
ARG NODEJS_PATH_ROOT
ARG NODEJS_PATH_SERVER

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV NODE_ENV=development

COPY ${PATH_ROOT}/certificate/. /etc/certificate/
COPY ${PATH_ROOT}/nodejs_server/. /home/node/server/
COPY ${PATH_ROOT}/entrypoint_nodejs.sh /usr/local/bin/entrypoint.sh

# System
RUN cd ~ \
&& chmod +x /usr/local/bin/entrypoint.sh \
&& apt-get update && apt-get install -y --no-install-recommends \
sudo \
nano \
tzdata \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Npm
&& npm install -g @vue/cli \
&& npm install -g terser \
&& npm install -g sass \
&& npm install -g pm2 \
# Server
&& cd ${NODEJS_PATH_SERVER} \
&& npm cache clear --force \
&& npm install \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

EXPOSE ${NODEJS_PORT_HTTP} ${NODEJS_PORT_HTTPS} ${NODEJS_PORT_VUE} ${NODEJS_PORT_VUE_APP}