import Setting from "../images/setting.svg";
import Explore from "../images/explore.svg";
import Ssh from "../images/ssh.svg";
import VueJs from "../images/vuejs.svg";
import Git from "../images/git.svg";
import Terser from "../images/terser.svg";
import Sass from "../images/sass.svg";
import NodeJs from "../images/nodejs.svg";
import Apache from "../images/apache.svg";
import Php from "../images/php.svg";
import MySql from "../images/mysql.svg";
import PostgreSql from "../images/postgresql.svg";
import Redis from "../images/redis.svg";
import MongoDb from "../images/mongodb.svg";

export const setting: string = Setting;
export const explore: string = Explore;
export const ssh: string = Ssh;
export const vueJs: string = VueJs;
export const git: string = Git;
export const terser: string = Terser;
export const sass: string = Sass;
export const nodeJs: string = NodeJs;
export const apache: string = Apache;
export const php: string = Php;
export const mySql: string = MySql;
export const postgreSql: string = PostgreSql;
export const redis: string = Redis;
export const mongoDb: string = MongoDb;
